const  types = {
    SET_CARDS:'SET_CARDS',
    ADD_CARD:'ADD_CARD',
    DELETE_ONE_CARD:'DELETE_ONE_CARD',
    DELETE_CARD_ID:'DELETE_CARD_ID',
    EDIT_CARD:'EDIT_CARD',
    SET_OR_REMOVE_LOADING:'SET_OR_REMOVE_LOADING',
    DELETE_CHECKED_CARDS:'DELETE_CHECKED_CARDS',
    GET_SINGLE_CARD:'GET_SINGLE_CARD',
    TOGGLE_OPEN_MODAL:'TOGGLE_OPEN_MODAL',
    TOGGLE_CONFIRM_MODAL:'TOGGLE_CONFIRM_MODAL',
    TOGGLE_CHECK_CARD:'TOGGLE_CHECK_CARD',
    TOGGLE_CHECK_ALL_CARDS:'TOGGLE_CHECK_ALL_CARDS',
    TOGGLE_OPEN_EDIT_MODAL:'TOGGLE_OPEN_EDIT_MODAL',
    DELETE_SINGLE_CARD:'DELETE_SINGLE_CARD',
    OPEN_EDIT_MODAL:'OPEN_EDIT_MODAL',

}
export default types