const  types = {
    SET_CARDS:'SET_CARDS',
    ADD_CARD:'ADD_CARD',
    DELETE_ONE_CARD:'DELETE_ONE_CARD',
    DELETE_CARD_ID:'DELETE_CARD_ID',
    EDIT_CARD:'EDIT_CARD',
    SET_OR_REMOVE_LOADING:'SET_OR_REMOVE_LOADING',
    DELETE_CHECKED_CARDS:'DELETE_CHECKED_CARDS',
    GET_SINGLE_CARD:'GET_SINGLE_CARD'
}
export default types